version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter build web

      # TODO: address these at a later date
      # - run: flutter analyze --no-fatal-infos lib
      # Broken web compiling: - run: flutter test
      # Missing google secrets json file: - run: flutter build apk --debug

